gen:
	@protoc --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
	 	api/oms.protohttps://www.skool.com/self-made-engineer/classroom/60cca559?md=a325f576ab9246dca239b58e2c253826